### ISSUE TITLE
Version 1.2 discussion

### ISSUE THREAD

**Issue by zsoltk** [zsoltk/paperwork#10]
A more generic, pluggable approach:
- make the plugin VCS agnostic, don't generate `gitSha` by default
- `buildTime` can stay, it disturbs no one if left unused (right?)
- or, in another approach, absolutely nothing is generated by default
- the current plugin functionality (git hash and build time generation) would move into public helper methods of the `PaperworkPluginExtension`, so they are easy to invoke if needed, and can be easily extended (e.g. new helpers for other version control systems)
- plugin parameter `extras` would be removed, as extras would now live inside the `set` block
- the configuration in this case would look something like:

``` groovy
paperwork {
    env = ['ENV1', 'ENV2']
    set = [
        buildTime: buildTime(),
        gitSha: gitSha(),
        mydata1: 'foo bar',
        mydata2: 'lorem ipsum',
    ]
}
```
- new runtime method `String get(String key)` would be added to access values set in the configuration block
- runtime methods `getGitSha()` and `getBuildTime` would now merely translate to `get("gitSha")` and `get("buildTime")` respectively
- maybe move `env` inside the `set` block, too, and provide an `env(String key)` helper method for them in `PaperworkPluginExtension`? Or is it better the current way? Both approach have pros and cons.

**Comment by zsoltk** [comment]
@vanniktech @artem-zinnatullin

**Comment by artem-zinnatullin** [comment]
> `buildTime` can stay, it disturbs no one if left unused (right?)

I'd remove it too because one may want format 1, another — format 2 and so on.

What if Paperwork will be just an easy way to write a file to assets and read it in the app? Plus samples for frequently used things like git sha and build time? That would make it useful for a lot of projects!

Not sure I understand purpose of `env`, why not just give map-like api where you define key and value? :)

**Comment by vanniktech** [comment]
Yup I'm basically on the same side as @artem-zinnatullin. Let us just easily write an asset file and give us a set of API methods to get that information. The important point is that we don't break the incremental build feature.

About the `env` topic. Correct me if I'm wrong but right now with 1.1 I can get the System enviroments variables of the computer / machine it was built on, correct? While this seems super nice, I don't see any particular case I'd use that.

I think all in all just a plain key value map is enough. Then you also don't need to distinguish between `env` and `set`. 

Though maybe some build in functions would be nice. (Just for handiness)

``` groovy
gitSha()
mercurialRevisionHash() // or any other VCS
buildTime(dateFormat) // for instance hh:mm:ss
systemEnvironmentVariables() // if you're really fancy provide a method to add those environmentvariables to the defined set
```

**Comment by vanniktech** [comment]
As for the `buildTime` why not simply provide a timestamp. And then everyone can display it the way it should be.

**Comment by artem-zinnatullin** [comment]
I'd just don't put `buildTime` into the library because you know Groovy so dynamic that writing build scripts with it is very non-obvious process.

I'd say that plugin puts **nothing** to the file and you should put required key-value pairs yourself, here are some examples: git, build time, etc.  Does it make sense for you guys?

**Comment by artem-zinnatullin** [comment]
@zsoltk if you don't mind I can invite more developers into discussion because who knows, maybe I and @vanniktech are not very representative :)

// I really think that this plugin will be used in a huge amount of projects so we should make it as obvious as possible.

**Comment by zsoltk** [comment]
> `mercurialRevisionHash() // or any other VCS`

Yep, that's what I meant by helper methods. We could provide a bunch of those and let everyone use the ones they need.

> `buildTime(dateFormat) // for instance hh:mm:ss`

I wouldn't throw out `buildTime()`, nor enforce a timestamp. Letting the users pass in their desired format seems nice enough. One problem could be the timezone (which requires a TimeZone object), but that's easy to detect (format contains 'Z' ?) if we want to be super nice. If not, the user can use their own value instead of calling the helper method.

**Comment by zsoltk** [comment]
@artem-zinnatullin sure, go ahead :)

**Comment by zsoltk** [comment]
If there's no further input, I'd like to move along the lines discussed so far. Any further ideas can be considered in future versions.
- the main direction is to allow generating key-value pairings with nothing being generated by default
- helper methods for the most commonly used methods, contributions are very welcome
- `buildTime(format)` helper which takes format string as an argument and automatically handles creating the TimeZone object if a 'Z' is detected in the format (as I guess it's fairly common to need that information)
- `env` as a standalone key is scraped along with its runtime counterpart
- an `env()` helper may or may not be added though

Can we agree on this?

**Comment by vanniktech** [comment]
Sounds good :+1:

On 3 January 2016 22:43:13 CET, Zsolt Kocsi notifications@github.com wrote:

> If there's no further input, I'd like to move along the lines discussed
> so far. Any further ideas can be considered in future versions.
> - the main direction is to allow generating key-value pairings with
>   nothing being generated by default
> - helper methods for the most commonly used methods, contributions are
>   very welcome
> - `buildTime(format)` helper which takes format string as an
>   argument and automatically handles creating the TimeZone object if a
>   'Z' is detected in the format (as I guess it's fairly common to need
>   that information)
> - `env` as a standalone key is scraped along with its runtime
>   counterpart
> - an `env()` helper may or may not be added though
> 
> Can we agree on this?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/zsoltk/paperwork/issues/10#issuecomment-168542877

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vanniktech** [comment]
Let's release 1.2?

**Comment by zsoltk** [comment]
It's out!

**Comment by zsoltk** [comment]
Thank you for your contributions!

**Comment by vanniktech** [comment]
@zsoltk no worries. Thanks for the plugins. I'll try 1.2 out for sure.

**Comment by artem-zinnatullin** [comment]
// JFYI I will be very busy next 2 weeks and will react slowly, but feel free to do a PR for #qualitymatters app and I'll try to review it at free time.

@zsoltk thanks for your work on the plugin and @vanniktech for contributions! I'll take a look at v1.2 on Monday and probably will integrate it with our production app :shipit:
