### ISSUE TITLE
Put some build time comparison  into README

### ISSUE THREAD

**Issue by artem-zinnatullin** [zsoltk/paperwork#11]
Would be nice to see value of the plugin:
1. Clean and incremental build with regular `buildConfigField` approach
2. Clean and incremental build with Paperwork

As an example, you can use `buildTime` with seconds so it will 100% have a new value for each build.

**Comment by zsoltk** [comment]
Clean build time holds no informational value, it's almost the same regardless of method used. Apart from that, agreed.

**Comment by artem-zinnatullin** [comment]
Nice! :+1:
