### ISSUE TITLE
Paperwork.setFileName does not invalidate json

### ISSUE THREAD

**Issue by vanniktech** [zsoltk/paperwork#21]
Calling `setFileName` on an already constructed object and then `get('mykey')` would still try to find it on the old file.

To be honest I'd remove the entire function. One Paperwork object is for one Paperwork file. If you need another one just construct another object.

**Comment by zsoltk** [comment]
Yes, setting `json = null;` at the end of `setFilename()` would be needed.

My intention was never to handle multiple files with a single object, however.

Some DI solutions can inject your object if it has either an empty constructor or one with only a `Context` object as a parameter (I'm looking at you, AndroidAnnotations). I thought maybe if you had to use that constructor, but still wanted to override the default filename, you would do it after injection, manually, and that's what the method is for.

Although I would argue with myself again, that injecting `Paperwork` would require extending the class and adding some annotations (e.g. `@Inject`, or in the case of AndroidAnnotations, `@EBean`), and one can set the desired filename there anyway by calling `super(context, "myFilename.json")` in the child constructor.

So yes, the method can be removed.
