### ISSUE TITLE
use jGit instead of git on shell

### ISSUE THREAD

**Issue by friedger** [zsoltk/paperwork#37]
To better support different build environments it would be nice to use e.g.
https://github.com/ajoberstar/grgit

**Comment by zsoltk** [comment]
Thanks for bringing this to my attention, cool project!

What do you mean by better supporting different build environments and how can grgit help in that?

Also, as I saw, it's lacking support for git describe parameters, which paperwork needs.

**Comment by zsoltk** [comment]
@friedger if there's no further input, I will be closing this.

**Comment by mstevens83** [comment]
I think what @friedger means it that by using jGit Paperwork would no longer rely on the presence of a working installation of the git cmdln tools on the machine (available on the PATH).
Some GUI-loving users may for example only use something like TortoiseGit and not have the cmdln git tools installed at all.
