### ISSUE TITLE
gitBranch() method fails build if no git repo present

### ISSUE THREAD

**Issue by kevinmost** [zsoltk/paperwork#44]
If I try to include `gitBranch()` in a Paperwork config for a project with no git repo, I get an error when trying to sync the Gradle file.

The message is: `Error:Cause: index is out of range 0..-1 (index = 0)`

I'd be happy to try to take this on and submit a PR if it helps.

**Comment by kevinmost** [comment]
As a small note, all of the other methods (`gitSha()`, `gitTag()`, `gitInfo()`) that I've used don't make the build error out. This one probably just needs a guard statement somewhere?

**Comment by zsoltk** [comment]
Tbh why use git related helpers when you don't have a git repo in your project ;)

But sure, it shouldn't die like that. If anything, then a meaningful error message would be the way to go. Feel free to submit a PR if you'd like to contribute.

**Comment by kevinmost** [comment]
Yeah, I just thought it was a little bit inconsistent because the others happen to work, and this one hits an error.

Also, the error message, as you said, is really cryptic. I was copying my build.gradle from an old project into a new one, and was really confused why it was erroring out. I just wasn't up to the step of running `git init` in that project's folder yet.

Will do a PR, it looks like a fairly simple problem.

**Comment by zsoltk** [comment]
@kevinmost any progress so far?

**Comment by zsoltk** [comment]
@kevinmost I'm closing this. If you wish to contribute, feel free to message later.
