### ISSUE TITLE
gitBranch() throws an exception when grade build started from shell on MacOS

### ISSUE THREAD

**Issue by dkorobtsov** [zsoltk/paperwork#48]
steps to reproduce:
bash gradlew clean --assembleDebug

Build fails with following exception:

14:30:24.052 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:30:24.053 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Where:
14:30:24.053 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Build file ..../build.gradle' line: 222
....
14:30:24.065 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.IndexOutOfBoundsException: index is out of range 0..-1 (index = 0)
14:30:24.066 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at hu.supercluster.paperwork.plugin.PaperworkPluginExtension.gitBranch(PaperworkPluginExtension.groovy:29)
14:30:24.067 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:464)
14:30:24.067 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:176)
14:30:24.068 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
14:30:24.068 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
14:30:24.069 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:59)
14:30:24.069 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at build_o48xeummu5kfiaeuusfk364a$_run_closure4.doCall(..../app/build.gradle:222)

14:30:24.070 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 62 more
14:30:24.070 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
14:30:24.070 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
14:30:24.071 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED

Looks like this line causes exceptions:
https://github.com/zsoltk/paperwork/commit/e42b963e80b375c6aefc97688f0d2b4105004feb

**Comment by flopic** [comment]
@dkorobtsov I've had the same problem on my Mac. 
How to fix:
Please upgrade git to the latest versoin (2.16.1) https://www.michaelcrump.net/step-by-step-how-to-update-git/

**Comment by dkorobtsov** [comment]
Yeah, sounds like a solution, thanks. 
In general solved this issue long ago just the same way. 
Suppose it makes sense to close the ticket.

**Comment by rhoadster91** [comment]
This problem seems to occur on some machines where 'git branch' returns a "paged" result and the `gitBranch()` method doesn't find the current branch (marked with *) in the first displayed page. The solution would be to use the `--no-pager` flag [in this class](https://github.com/zsoltk/paperwork/blob/57ce032bdcd10403b759a65938ad307aa5d7def0/paperwork-plugin/src/main/groovy/hu/supercluster/paperwork/plugin/PaperworkPluginExtension.groovy) so that any machine that is configured to use pager for git branch command will still result in expected behaviour.

**Comment by zsoltk** [comment]
You can use this instead of the `gitBranch()` helper in the meantime, should work:

```
paperwork {
    set = [
            gitBranch : shell('git rev-parse --abbrev-ref HEAD')
    ]
}
```
