### ISSUE TITLE
Write tests for paperwork-plugin

### ISSUE THREAD

**Issue by zsoltk** [zsoltk/paperwork#8]

**Comment by zsoltk** [comment]
Featureset to write tests for:

``` groovy
paperwork {
    set = [
            git1:       gitSha(),
            git2:       gitTag(),
            git3:       gitInfo(),
            buildTime1: buildTime(),
            buildTime2: buildTime("yyyy-MM-dd'T'HH:mm:ss'Z'"),
            buildTime3: buildTime("yyyy-MM-dd'T'HH:mm:ss'Z'", "GMT+1"),
            foo:        shell("scripts/foo.sh"),
            someEnv:    env("SOME_ENV")
    ]
}
```

**Comment by zsoltk** [comment]
@vanniktech Do we want to write tests for the git related helpers? The strings they provide lie outside the scope of the project, and the most that can be done is to duplicate the logic already written in the helpers and compare against that in the tests. Which makes me wonder if it's worth at all. What do you think?

**Comment by vanniktech** [comment]
Nice tests you wrote there for the other functions :+1:

Yeah about those git functions, I don't know what we should do with those to be honest. We could do it like with the shell test. Basically building up the environment through the command line, though that seems like a lot of hassle just for testing it.

**Comment by zsoltk** [comment]
I started doing exactly that, then stopped and wrote my comment above :) Besides, it's not possible to change working directory in the tests (http://stackoverflow.com/questions/18179200/how-to-change-the-current-working-directory-in-groovy), git only has a directory switching param for git init (or am I wrong?), and I wouldn't like to pollute a non-temporary dir with created files. If anything goes wrong, the cleanup code will not be executed. So our only option seems to be to test the helpers against the very same code written in them.

I'm asking, because 1.2 could be released or not, depending on this matter.

(Another question for another topic: should we open an issue to write integration tests? Basically like paperwork-example, and testing the TextView values.)

**Comment by vanniktech** [comment]
Maybe we could put a git submodule into the repository into the test directory under assets or some other directory and execute the test on this one.

Yup let's open an issue for writing integration tests.

**Comment by zsoltk** [comment]
I'm not sure how you mean it. The working directory will still be the module being tested, and any shell commands will be executed there. Am I missing something here?

**Comment by vanniktech** [comment]
Isn't it possible that we put an already created git repository under `paperwork-plugin/test/assets` and let the plugin execute the command (for instance getting the git commit) from that repository?

I've never tried this so I'm not really sure either.

**Comment by zsoltk** [comment]
I tried to create a temp directory under the build dir (along the same lines I do it in the test for `shell()`) and use that (so no submodule magic is needed), but I failed miserably.

Well maybe I did something wrong (first time I ever played around with this), but setting the directory `ProjectBuilder.builder().withProjectDir(baseDir).build()` did not change the execution context, it was still the paperwork-plugin module dir. When I tried to execute the shell command `cd`, it threw an exception. Then I googled around, and I posted here that stackoverflow page I found. Maybe there's another way, but I'm not sure how. Until it's figured out, well, how will we execute the git commands in any other directory?

**Comment by vanniktech** [comment]
Hmm that's a bummer. I'll see if I can think of anything. If not I'd suggest we will leave it for now and maybe just create a ticket to track this one if that's the only test that is essentially missing.

**Comment by vanniktech** [comment]
That can be closed now, right?

**Comment by zsoltk** [comment]
Yep.
