### ISSUE TITLE
Write tests for paperwork-runtime

### ISSUE THREAD

**Issue by zsoltk** [zsoltk/paperwork#9]

**Comment by zsoltk** [comment]
[removed]

**Comment by zsoltk** [comment]
I should have posted the above example code in #8 instead, my mistake. Fixing now.

**Comment by vanniktech** [comment]
@zsoltk did you write any more test for the Paperwork runtime API locally and they are not yet pushed or can I start writing more?

**Comment by zsoltk** [comment]
Go ahead!

**Comment by vanniktech** [comment]
Done #29

**Comment by zsoltk** [comment]
Do we need anything else here? Or can this be closed?

**Comment by vanniktech** [comment]
Can be closed. Any further changes to the runtime should have unit tests already added to them.
